<?php

return array(
  'eboekhouden_username' => array(
    'group_name' => 'E-boekhouden settings',
    'group' => 'eboekhouden',
    'name' => 'eboekhouden_username',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
    'default' => '',
    'add' => '4.3',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Username',
    'description' => 'Username for SOAP api E-boekhouden.nl',
    'help_text' => '',
  ),
  'eboekhouden_code1' => array(
    'group_name' => 'E-boekhouden settings',
    'group' => 'eboekhouden',
    'name' => 'eboekhouden_seccode1',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
    'default' => '',
    'add' => '4.3',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Security code 1',
    'description' => '1st security code for SOAP api E-boekhouden.nl',
    'help_text' => '',
  ),
  'eboekhouden_code2' => array(
    'group_name' => 'E-boekhouden settings',
    'group' => 'eboekhouden',
    'name' => 'eboekhouden_seccode2',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
    'default' => '',
    'add' => '4.3',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Security code 2',
    'description' => '2nd security code for SOAP api E-boekhouden.nl',
    'help_text' => '',
  ),
);
