<?php

return array(
  'eboekhouden_cursor' => array(
    'group_name' => 'SOAP api settings',
    'group' => 'eboekhouden',
    'name' => 'eboekhouden_cursor',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
    'default' => '',
    'add' => '4.3',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'SOAP mutations cursor',
    'description' => 'Mutations cursor for SOAP api connection',
    'help_text' => '',
  ),
  'eboekhouden_soap_url' => array(
    'group_name' => 'SOAP api settings',
    'group' => 'eboekhouden',
    'name' => 'eboekhouden_soap_url',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
    'default' => '',
    'add' => '4.3',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'SOAP url',
    'description' => 'URL for SOAP api connection',
    'help_text' => '',
  ),
  'eboekhouden_username' => array(
    'group_name' => 'SOAP api settings',
    'group' => 'eboekhouden',
    'name' => 'eboekhouden_username',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
    'default' => '',
    'add' => '4.3',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Username',
    'description' => 'Username for SOAP api connection',
    'help_text' => '',
  ),
  'eboekhouden_seccode1' => array(
    'group_name' => 'SOAP api settings',
    'group' => 'eboekhouden',
    'name' => 'eboekhouden_seccode1',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
    'default' => '',
    'add' => '4.3',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Security code 1',
    'description' => '1st security code for SOAP api connection',
    'help_text' => '',
  ),
  'eboekhouden_seccode2' => array(
    'group_name' => 'SOAP api settings',
    'group' => 'eboekhouden',
    'name' => 'eboekhouden_seccode2',
    'type' => 'String',
    'quick_form_type' => 'Element',
    'html_type' => 'Text',
    'default' => '',
    'add' => '4.3',
    'is_domain' => 1,
    'is_contact' => 0,
    'title' => 'Security code 2',
    'description' => '2nd security code for SOAP api connection',
    'help_text' => '',
  ),
);
